# 예외 처리

## 목차

## 1. 예외 처리

### 1-1. 에러(error)
**에러**는 시스템에 비정상적인 상황이 생겼을 때 발생한다. 외부 요인일 수도 있고, 프로그램 구동 중에 발생하는 치명적 오류일 수도 있다. 이러한 에러들은 개발자가 예측하거나 처리할 수 없는 영역이다.

에러의 종류는 다음과 같다.

|에러의 종류|상황|
|:-:|-|
|OutOfMemoryError|프로그램 실행 중 메모리 부족|
|IOError|입출력 에러|
|StackOverFlowError|가용 메모리 부족 현상, 재귀 호출 문제 시 발생|


### 1.2 예외(exception)
예외란 대체로 프로그램 구동 중에 나타나는 오류들을 말한다. 문법적으로는 문제없어 보이지만 실제 운영 중에 생기는 문제들이다. 예외는 **체크 예외**와 **비체크 예외** 두 가지가 있다.
<br/>
**체크 예외**는 자바 소스를 컴파일하는 과정에서 검사하며, 보통 문법적으로 강제하여 예외 처리를 하는 경우이고, **비체크 예외**는 컴파일 과정에서 검사하지 않으므로 사용자의 경험이나 테스트로 찾아야 하는 경우가 있다. 보통 개발자를 힘들게 하는 경우가 이 비체크 예외들이다.

체크 예외와 비체크 예외를 구분하는 기준은 다음과 같다.

|구분|체크 예외|비체크 예외|
|:-:|-|-|
|처리 여부|문법적으로 예외 처리를 강제함<br/>반드시 처리 해야 함|문법적으로 강제하지 않음<br/>개발자의 판단에 의해 처리|
|확인 시점|컴파일 단계|실행 단계|
|예외 클래스|Runtime Exception을 제외한 모든 예외<br/>IOException<br/>SQLException등|Runtime Exception의 자식 클래스 모두 포함<br/>NullPointerException<br/>IndexOutOfBoundException<br/>ClassNotFoundException|

## 2. 예외 클래스
자바는 객체 지향 언어이기 때문에 프로그램에서 발생하는 예외들은 클래스의 형태로 제공된다.
<br/>
다음은 예외 처리에 대한 클래스 관계도이다.

[예외 클래스 관계도 사진]

최상위의 Throwable을 상속받은 에러와 예외가 있다. 에러는 시스템상의 심각한 수준의 오류이기 때문에 수습될 수 없는 반면에, 예외는 개발자가 로직을 추가하여 처리할 수 있다. 그림에 표기된 예외 클래스 중 자주 사용되는 예외에 대해 살펴보자.

### 2-1. NullPointException
`NullPointException`은 자바 프로그램에서 가장 빈번하게 발생하는 실행 예외이다. 객체가 제대로 생성되지 않은 상태에서 사용할 경우 발생한다. 우리가 객체를 선언하면 인스턴스는 객체의 주소를 가지게 되고, 그것글 통해 객체에 접근해 값을 가져온다. 그런데 객체는 정의되었는데 실제 메모리에 생성되지 않았을 경우, 예외가 발생한다.

> ### NullPointException 예외
> ```java
> public class Practice {
>     public static void main(String[] args) {
>         String[] strArray = null;
> 
>         System.out.println("strArray[0] = " + strArray[0]);  
>     } 
> }
> ```
> ### 실행 결과
> ```
> Exception in thread "main" java.lang.NullPointerException: Cannot load from object array because "strArray" is null
>     at test.main(test.java:5)
> ```

### 2-2. NumberFormatException
`NumberFormatException`은 잘못된 문자열을 숫자로 형 변환할 때 발생한다. 숫자 형태의 문자열은 정수 타입으로 변환할 수 있으나 문자가 포함되거나 실수 형태의 문자열은 변환할 수 없다.

> ### NumberFormatException 예외
> ```java
> public class Practice {
>     public static void main(String[] args) {
>         String str01 = "11";
>         String str02 = "11.2";
> 
>         // 정수 형태의 문자열을 정수로 변환
>         int num01 = Integer.parseInt(str01);
> 
>         System.out.println("String to int : " + num01);
> 
>         // 실수 형태의 문자열을 정수로 변환
>         int num02 = Integer.parseInt(str02);
> 
>         System.out.println("String to int : " + num02);
>     } 
> }
> ```
> ### 실행 결과
> ```
> Exception in thread "main" java.lang.NumberFormatException: For input string: "11.2"
>     at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
>     at java.base/java.lang.Integer.parseInt(Integer.java:661)
>     at java.base/java.lang.Integer.parseInt(Integer.java:777)
>     at test.main(test.java:12)
> ```

### 2-3. ArrayIndexOutOfBoundsException
`ArrayIndexOutOfBoundsException`은 배열에서 인덱스 범위를 초과해 사용할 때 발생한다.

> ### ArrayIndexOutOfBoundsException 예외
> ```java
> public class Practice {
>     public static void main(String[] args) {
>         int[] arr = {1, 6, 7, 9, 10};
>         System.out.println(arr[6]);
>     } 
> }
> ```
> ### 실행 결과
> ```
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 5
>     at test.main(test.java:4)
> ```

## 3. 예외 처리 문법

### 3-1. 예외 처리 과정

[예외 처리 과정 사진]

```
1. 코드 진행 중 예외가 발생하면 JVM에게 알린다.
2. JVM은 발생한 예외를 분석하여 알맞은 예외 클래스를 생성한다.
3. 생성된 예외 객체를 발생한 지점으로 보낸다.
4. 예외가 발생한 지점에서 처리하지 않으면 프로그램은 비정상 종료된다.
```

위와 같이 예외가 발생하면 시스템(JVM)에서 분석하여 우리가 배운 예외 클래스 중 알맞은 것을 발생시키고 발생 지점으로 던지게 된다. 이를 처리하지 않으면 프로그램은 비정상으로 종료된다. 그래서 우리는 넘어온 예외를 처리해 프로그램을 비정상으로 종료되지 않고, 구동할 수 있도록 해야한다.

### 3-2. try-catch 구문
예외를 처리하는 가장 기본 문법은 try-catch 문이다.
<br/>
try-catch 문의 기본 구조는 다음과 같다.

```java
try {
    // 예외가 발생할 가능성이 있는 코드
} catch (예외 클래스 명 e) {
    // 예외 처리 코드    
}
```

발생한 예외를 처리하기 위해서 우리는 try-catch 구문을 사용하게 된다. 예외가 발생할 가능성이 있는 코드는 try {...} 안에 작성하고 catch 메서드는 시스템으로부터 넘어오는 예외 클래스를 받아서 처리한다.

> ### 예외 처리 1
> ```java
> public class Practice {
>     public static void main(String[] args) {
>         int result = 0;
> 
>         try {
>             result = 10 / 0;
>             System.out.println("나누기 결과 : " + result);
>         } catch (arithmeticException e) {
>             System.out.println("0으로 나누기 할 수 없습니다.");
>         }
>         System.out.println("프로그램 종료.");
>     } 
> }
> ```
> ### 실행 결과
> ```
> 0으로 나누기 할 수 없습니다.
> 프로그램 종료.
> ```

또한 예외를 처리할 때 `Exception` 클래스를 이용하면 모든 예외를 처리할 수 있다. `Exception`은 모든 예외 클래스의 최상위 객체이기 때문에 catch에서 사용하면 모든 예외 처리가 가능하다.

## 3-3. 다중 catch 사용하기
프로그램을 구동할 때 하나의 예외만 발생한다면 처리하기는 어렵지 않다. 하지만 try 구문 안에서 예외는 다양하게 발생할 수 있다. 만약 기존과 같은 방법으로 처리한다면 하나의 예외를 제외하고는 제대로 처리할 수 없다. 이 때, 다중 catch 문을 사용한다. 다중 catch 문은 예외별로 예외 처리 코드를 다르게 하여 다양한 예외를 처리할 수 있다.

```java
try {
    ...
} catch (NullPointerException e) {
} catch (ArithmeticException e) {
}
```

catch 문은 하나의 예외를 처리하도록 되어있다. 코드에서 하나의 예외를 발생하면 그 위치에서 실행을 멈추고 해당 예외를 처리하는 catch 블록으로 이동하게 된다.

> ### 다중 예외 처리
> ```java
> public class Practice {
>     public static void main(String[] args) {
>         Scanner scan = new Scanner(System.in);
> 
>         try {
>             int[] cards = {4, 5, 1, 2, 7, 8};
>             System.out.println("몇 번째 카드를 뽑으시겠습니까? >>");
>             
>             int cardIndex = scan.nextInt();
>             System.out.println("뽑은 카드 번호는 : " + cards[cardIndex]);
>         } catch (InputMismatchException e) {
>             System.out.println("잘못 입력하셨습니다. 숫자만 가능합니다.");
>         } catch (ArrayIndexOutOfBoundsException e) {
>             System.out.println("해당 번호의 카드는 없습니다.");
>         }
> 
>         System.out.println("프로그램 종료");
>         scan.close();
>     } 
> }
> ```
> ### 실행 결과
> ```
> 몇 번째 카드를 뽑으시겠습니까? >>
> 11
> 해당 번호의 카드는 없습니다.
> 프로그램 종료
> ```

### 3-4. finally
`finally` 블록은 예외 발생 유무와 상관없이 실행되는 구문이며 생략할 수 있다. 예외 처리를 할 때, 예외외 상관없이 반드시 처리해야 하는 구문들을 작성할 때 사용되며, 보통 외부 연동이나 예외가 발생해도 정상 종료되어야 할 구문들에서 사용된다. catch 구문 다음에 finally를 작성한다.

> ### finally 문법
> ```java
> public class Practice {
>     public static void main(String[] args) {
>         Scanner scan = new Scanner(System.in);
> 
>         try {
>             System.out.println("점수를 입력하세요 >>");
>             int score = scan.nextInt();
>             
>             if (score >= 60) {
>                 System.out.println("합격입니다.");
>             } else {
>                 System.out.println("아쉽네요. 불합격입니다.");
>             }
>         } catch (InputMismatchException e) {
>             System.out.println("키보드 입력이 올바르지 않습니다.");
>         } finally {
>             scan.close();
>             System.out.println("프로그램 종료");
>         }
>     } 
> }
> ```
> ### 실행 결과
> ```
> 점수를 입력하세요 >>
> 87
> 합격입니다.
> 프로그램 종료
> ```
> 이 예제는 Scanner를 사용해 점수를 입력받고 결과를 출력하는 간단한 예제이다. 우리가 만약 키보드를 잘못 입력했다면 예외 처리가 발생할 것이다. 그러면 프로그램 종료 시 Scanner를 종료시키는 구문을 실행할 수 없게 된다. 따라서 finally 블록에서 처리해 Scanner를 안전하게 종료하고 프로그램을 마쳐야 한다.


## 4. 예외 던지기
우리가 호출한 메서드에서 예외가 발생할 경우, 학습한 대로 메서드 내부에서 try-catch 문으로 예외를 처리할 수 있었다. 그런데 메서드 내부에서 예외를 처리하지 않고 미룬 후, 해당 메서드를 호출한 쪽에서 예외를 처리하도록 하는 방법도 있다. 우리는 그것을 `예외 던지기` 라고 한다.

예외 던지기는 `throws` 키워드를 사용한다. 메서드 뒤에 throws 키워드를 사용하여 던지기 할 예외 객체를 붙여주면 된다. 예외 객체는 여러 개를 던질 수 있으며, 여러 개를 던질 시에는 콤마(`,`)로 구분해서 나열해준다.

예외를 직접 처리하는 경우와 예외를 던져서 호출한 쪽에 전가하는 경우를 비교해보자.

> ### 예외를 직접 처리하는 경우
> ```java
> public int divide(int x, int y) {
>     try {
>         return x/y;
>     } catch (ArithmeticException e) {
>         System.out.println("0으로 나눌 수 없습니다.");
>     }
> }
> 
> public class Practice {
>     public static void main(String[] args) {
>         int result = divide(10, 0);
>         System.out.println("나누기 : " + result);
>     } 
> }
> ```
> ### 예외를 던져서 호출한 쪽에 전가하는 경우
> ```java
> public int divide(int x, int y) throws ArithmeticException {
>     return x/y;
> }
> 
> public class Practice {
>     public static void main(String[] args) {
>         try {
>             System.out.println("나누기 : " + divide(10, 0));
>         } catch (ArithmeticException e) {
>             System.out.println("0으로 나눌 수 없습니다.");
>         }
>     } 
> }
> ```
> 예외 던지기를 하는 이유는 메서드에서 예외를 각각 처리하면 메서드 자체의 코드가 길어기저나, 유지 보수 측면에서 효율이 떨어질 수 있다. 이때, 메서드를 호출하는 쪽에서 예외를 처리해 주면 좀 더 수월하게 처리할 수 있다.

### 4-1. 임의의 예외 처리 방법
프로그램을 작성하다 보면 코드의 오류로 발생하는 예외도 있지만, 프로그램의 규칙에 위배되어 예외를 발생해야 하는 경우도 있다. 만약, 프로그램의 규칙에 위배되어 예외를 발생해야 할 경우, 임의로 예외를 발생시킬 수 있다.

임의의 예외 처리는 다음과 같은 특징을 가지고 있다.

- **정의** : 예외 발생 상황이 아니더라도, 필요에 의해 강제로 예외를 발생시키는 기능
- **발생 방법** : throw new [예외 객체] ([메시지]);
- **발생 위치** : try-catch 내부 또는 메서드에 예외 던지기가 있는 경우
- **용도** : 개발자가 예외를 의도하는 위치

> ### 임의의 예외 처리
> ```java
> public class Practice {
>     public static void main(String[] args) {
>         Scanner scan = new Scanner(System.in);
> 
>         int val = 0;
>         while (true) {
>             try {
>                 System.out.println("숫자를 입력하세요(0 ~ 50) : ");
>                 val = scan.nextInt();
> 
>                 if (val == -1) {
>                     break;
>                 }
> 
>                 if (val < 0 || val > 50) {
>                     // 임의의 예외 발생
>                     throw new Exception("숫자의 허용범위가 아닙니다.");
>                 }
>             } catch (Exception e) {
>                 scan.nextLine();
>                 System.out.println("에러 메시지 : " + e.getMessage());
>             }
>         }
> 
>         scan.close();
>         System.out.println("프로그램 종료.");
>     } 
> }
> ```
> ### 실행 결과
> ```
> 숫자를 입력하세요(0 ~ 50) :
> 51
> 에러 메시지 : 숫자의 허용범위가 아닙니다.
> 숫자를 입력하세요(0 ~ 50) :
> -1
> 프로그램 종료.
> ```

## 5. 사용자 정의 예외 처리
자바가 제공하는 예외 객체 외에도 개발자의 목적에 의해서 예외 객체를 만들 수 있으며, 이를 사용할 수 있다. 목적에 따라 공통기능을 지니는 예외 처리도 필요하기 때문에 개발자가 직접 예외를 생성하여 처리한다.
체크 예외를 만들고 싶다면, 최상위 객체인 `Exception`을, 비체크 예외를 만들고 싶을 때는 `RuntimeException`을 상속한다.

> ### 사용자 정의 예외
> ```java
> // 사용자 정의 예외 생성
> class InputErrorException extends Exception {
>     private String message;
>     public InputErrorException(String message) {
>         this.message = message;
>     }
> 
>     @Override
>     public String getMessage() {
>         return this.message;
>     }
> }
> 
> public class Practice {
>     public static void main(String[] args) {
>         // 스캐너 생성
>         Scanner scan = new Scanner(System.in);
>         try {
>             // 나이 입력
>             System.out.println("당신의 나이를 입력하세요 >>");
>             int age = scan.nextInt();
> 
>             if (age < 0) {
>                 // 1살 미안인 경우 입력 실패
>                 throw new InputErrorException("입력이 잘못되었습니다.");
>             }
> 
>             if (age > 19) {
>                 System.out.println("성인입니다.");
>             } else if (age > 13) {
>                 System.out.println("청소년입니다.");
>             } else if (age > 6) {
>                 System.out.println("어린이입니다.");
>             } else {
>                 System.out.println("아동입니다.");
>             }
>         } catch (InputErrorException e) {
>             System.out.println(e.getMessage());
>         } finally {
>             if (scan != null) {
>                 scan.close();
>             }
>         }
>     }
> }
> ```
> ### 실행 결과
> ```
> 당신의 나이를 입력하세요 >> -1
> 입력이 잘못되었습니다
> ```
